name: build-dev
on:
  push:
    branches:
      - Development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install angular
        run: npm install -g @angular/cli
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: running transform
        run: . build-dev.sh
      - uses: actions/upload-artifact@v3
        with:
          name: dev-build
          path: |
            Dev-Depictor-Frontend-Build.zip
            Dev-Depictor-Frontend-Build.zip
